version: '3.3'
services:
  phpfpm:
    image: php:7.2-fpm-alpine
    volumes:
      - "$BCPATH:/srv/httpd/symfony"
    configs:
      - source: php_config
        target: /usr/local/etc/php/php.ini
  redis:
    image: redis:4.0-alpine
  nginx:
    env_file: .env
    image: nginx:1.13-alpine
    ports:
      - "$NGINX_PORT:80"
    volumes:
      - "$BCPATH:/srv/httpd/symfony"
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf

configs:
  nginx_config:
    file: ./docker/etc/nginx/nginx.conf
  php_config:
    file: ./docker/etc/php.ini